### ISSUE TITLE
k3s-selinux-0.2-2.el7_8.noarch.rpm downloadable?

### ISSUE THREAD

**Issue by dbasinge** [rancher/k3s-selinux#14]
Is k3s-selinux-0.2-2.el7_8.noarch.rpm downloadable for somewhere? Can't find it on rpm.rancher.io.

**Comment by Oats87** [comment]
@dbasinge Apologies for the late reply.

https://github.com/rancher/k3s-selinux/releases/tag/v0.2.stable.1 is the latest release, i.e. `k3s-selinux-0.2-1.el7_8.noarch.rpm`.

We have moved the RPMs in our RPM repository, the new repo path is
for EL 7:
```
https://rpm.rancher.io/k3s/stable/common/centos/7/noarch
```
for EL 8:
```
https://rpm.rancher.io/k3s/stable/common/centos/8/noarch
```
